apiVersion: v2
annotations:
  catalog.cattle.io/display-name: CaaS Cluster Monitoring V3
name: caas-cluster-monitoring
description: A Helm chart for Rancher Cluster Monitoring V3
version: "1.0.3-rc0"
appVersion: "68.1.1"
icon: https://raw.githubusercontent.com/caas-team/caas-project-monitoring/main/logo.png
keywords:
- monitoring
dependencies:
- name: kube-prometheus-stack
  version: "68.1.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- condition: rkeEtcd.enabled
  name: rkeEtcd
  version: 0.2.1
  repository: file://./charts/rkeEtcd
- condition: rkeControllerManager.enabled
  name: rkeControllerManager
  repository: file://./charts/rkeControllerManager
  version: 0.2.1
- condition: rkeScheduler.enabled
  name: rkeScheduler
  repository: file://./charts/rkeScheduler
  version: 0.2.1
- condition: rkeIngressNginx.enabled
  name: rkeIngressNginx
  repository: file://./charts/rkeIngressNginx
  version: 0.2.1
- condition: rkeProxy.enabled
  name: rkeProxy
  repository: file://./charts/rkeProxy
  version: 0.2.1
- condition: hardenedKubelet.enabled
  name: hardenedKubelet
  repository: file://./charts/hardenedKubelet
  version: 0.2.1
- condition: rke2ControllerManager.enabled
  name: rke2ControllerManager
  repository: file://./charts/rke2ControllerManager
  version: 0.2.0
- condition: rke2Etcd.enabled
  name: rke2Etcd
  repository: file://./charts/rke2Etcd
  version: 0.2.0
- condition: rke2IngressNginx.enabled
  name: rke2IngressNginx
  repository: file://./charts/rke2IngressNginx
  version: 0.2.0
- condition: rke2Proxy.enabled
  name: rke2Proxy
  repository: file://./charts/rke2Proxy
  version: 0.2.0
- condition: rke2Scheduler.enabled
  name: rke2Scheduler
  repository: file://./charts/rke2Scheduler
  version: 0.2.0
sources:
- https://github.com/caas-team/caas-cluster-monitoring
- https://github.com/prometheus-community/helm-charts
maintainers:
- name: eumel8
  email: f.kloeker@telekom.de
  url: https://www.telekom.com
- name: puffitos
  email: bruno.bressi@telekom.de
  url: https://www.telekom.com
