apiVersion: v2
annotations:
  catalog.cattle.io/display-name: CaaS Cluster Monitoring V3
  catalog.cattle.io/requests-cpu: 1000m
  catalog.cattle.io/requests-memory: 1000Mi
name: caas-cluster-monitoring
description: A Helm chart for Rancher Cluster Monitoring V3
version: "0.0.1"
appVersion: "51.0.3"
icon: https://raw.githubusercontent.com/caas-team/caas-project-monitoring/main/logo.png
keywords:
  - monitoring
dependencies:
  - name: kube-prometheus-stack
    version: "51.0.3"
    repository: "https://prometheus-community.github.io/helm-charts"
sources:
  - https://github.com/caas-team/caas-cluster-monitoring
  - https://github.com/prometheus-community/helm-charts
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
  - name: puffitos
    email: bruno.bressi@telekom.de
    url: https://www.telekom.com
