{{- if .Values.caas.rancherMonitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
    metricRelabelings:
    {{ if .Values.global.cattle.clusterId }}
      - sourceLabels: [__address__]
        targetLabel: cluster_id
        replacement: {{ .Values.global.cattle.clusterId }}
    {{- end }}
    {{ if .Values.global.cattle.clusterName}}
      - sourceLabels: [__address__]
        targetLabel: cluster_name
        replacement: {{ .Values.global.cattle.clusterName }}
    {{- end }}
  jobLabel: rancher
  selector: {{ (lookup "apps/v1" "Deployment" "cattle-system" "rancher") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancher-metrics
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - ranchermetrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1   
kind: ClusterRoleBinding                                                                                                                       
metadata:                                                                                                                                      
  name: rancher-metrics
roleRef:                                         
  apiGroup: rbac.authorization.k8s.io          
  kind: ClusterRole                           
  name: rancher-metrics
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
