{{- if and .Values.caas.networkPolicies.allowEgress (not .Values.caas.networkPolicies.allowAllTraffic) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  egress:
    - {}
  podSelector: {}
  policyTypes:
    - Egress
{{- end }}
