{{- if and .Values.caas.networkPolicies.dynatrace (not .Values.caas.networkPolicies.allowAllTraffic) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-dynatrace
  namespace: cattle-monitoring-system
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            field.cattle.io/projectId: dynatrace
  podSelector:
    matchLabels:
      release: rancher-monitoring
  policyTypes:
    - Ingress
{{- end }}
