{{- if .Values.caas.allowEgress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  egress:
    - {}
  podSelector: {}
  policyTypes:
    - Egress
    - Ingres
{{- end }}
