{{ if .Values.caas.egressMicroservices }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: egress-to-microservices
spec:
  egress:
  - ports:
    - port: 9191
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          name: microservices
  podSelector:
    matchLabels:
      prometheus: "{{ .Release.Name }}-prometheus"
  policyTypes:
  - Egress
{{- end }}

