{{- if .Values.caas.networkPolicies.prometheusAuth }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-auth
spec:
  ingress:
    - ports:
      - port: 9091
        protocol: TCP
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
